google_analytics: UA-178410963-1
plugins:
  - jekyll-feed
  - jekyll-sitemap
include:
  - _pages
  - _projets
theme: jekyll-theme-cayman
repository: florianchapon/website
header_pages:
  - about
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /blog/:path/
  projets:
    output: true
    permalink: /:path/
title: Florian Chapon • Product manager • Grenoble
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
email: chapon.florian@gmail.com
description: Explore the portfolio of Florian Chapon, a product manager in
  electrochemistry based in Grenoble. Discover my work, including side projects
  in graphic design, video editing, coding, and more! tessst
footer:
  title: test footer info
  description: test description
