plugins:
  - jekyll-feed
  - jekyll-sitemap
include:
  - _pages
  - _projets
theme: jekyll-theme-cayman
repository: FleauxTV/website
header_pages:
  - about
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /blog/:path/
  projets:
    output: true 
    permalink: /:path/  
title: FleauxTV - Graphiste, Motion designer & Monteur vidéo
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
email: fleauxtv@gmail.com
description: Je suis un Graphiste, Motion designer & monteur vidéo basé près de
  Grenoble, FRANCE.  Vous trouverez sur ce site des exemples de réalisations,
  ainsi que les projets sur  lesquelles j'ai eu le plaisir de collaborer.
footer:
  social:
    - icon: fa-twitter
      name: Twitter
      link: https://twitter.com/FleauxTV
    - link: https://www.youtube.com/user/FleauxTV
      name: Youtube
      icon: fa-youtube
    - icon: fa-twitch
      name: Twitch
      link: https://www.twitch.tv/fleaux
  title: FleauxTV
  description: Graphic / motion designer, video editor
google_analytics: "UA-90344648-2"  
  
